server:
  port: 8081

spring:
  application:
    name: service-customer
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://localhost:27018/BootcampEverisS1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



